import { EBookCategory, IBook } from '../../books/models/book.model';

export const booksCatalogue: IBook[] = [
  {
    id: 1,
    name: 'Leadership',
    description: `This book combines an academically robust account of the major theories and models of leadership`,
    price: 22.95,
    category: EBookCategory.business,
    author: 'Dr. Peter G Northouse',
    createDate: new Date(2021, 0, 0),
    isAvailable: true,
    img: '/assets/book_covers/cover_leadership.jpg',
  },
  {
    id: 2,
    name: 'Becoming',
    description: 'An intimate, powerful, and inspiring memoir by the former First Lady of the United States',
    price: 12.83,
    category: EBookCategory.biographies,
    author: 'Michelle Obama',
    createDate: new Date(2018, 0, 0),
    isAvailable: true,
    img: './assets/book_covers/cover_becoming.jpg',
  },
  {
    id: 3,
    name: 'A Promised Land',
    description:
      'A Promised Land is a memoir by Barack Obama, the 44th President of the United States from 2009 to 2017',
    price: 23.97,
    category: EBookCategory.biographies,
    author: 'Barack Obama',
    createDate: new Date(2020, 0, 0),
    isAvailable: true,
    img: './assets/book_covers/cover_promised_land.jpg',
  },
  {
    id: 4,
    name: '1984',
    description: `“The Party told you to reject the evidence of your eyes and ears. It was their final, most essential command.”`,
    price: 6.38,
    category: EBookCategory.fiction,
    author: 'George Orwell',
    createDate: new Date(1950, 0, 0),
    isAvailable: false,
    img: './assets/book_covers/cover_1984.jpg',
  },
  {
    id: 5,
    name: 'Hidden Figures',
    description: `The American Dream and the Untold Story of the Black Women Mathematicians Who Helped Win the Space Race`,
    price: 20.98,
    category: EBookCategory.historical,
    author: 'Margot Lee Shetterly',
    createDate: new Date(2016, 0, 0),
    isAvailable: true,
    img: './assets/book_covers/cover_hidden_figures.jpg',
  },
  {
    id: 6,
    name: 'Made to Stick',
    description: `Why Some Ideas Survive and Others Die? This book is written for anyone who strives to craft messages that are memorable and lasting.`,
    price: 12.29,
    category: EBookCategory.business,
    author: 'Chip Heath',
    createDate: new Date(2007, 0, 0),
    isAvailable: true,
    img: '/assets/book_covers/cover_stick.jpg',
  },
];
